variables_order = "EGPCS"
upload_max_filesize = 100M
post_max_size = 120M
memory_limit = 256M
max_execution_time = 60
session.cookie_httponly = 1
session.use_strict_mode = 1
date.timezone = Asia/Manila
